### ISSUE TITLE
Emulator.kt should be called AdbDevice.kt

### ISSUE THREAD

**Issue by Sloy** [gojuno/commander#11]
I was trying to find the `AdbDevice` class implementation from Composer, and I couldn't find it on Composer or Commander navigating through GitHub. It took me a (pathetically) long time to find that the class is located in the [Emulator.kt](https://github.com/gojuno/commander/blob/master/android/src/main/kotlin/com/gojuno/commander/android/Emulator.kt) file.

I know it's a small detail, but since it only contains the AdbDevice class which includes both emulators and physical devices, I think it would be best to rename it. That way nobody else will feel as stupid as I did just now 😅 

I'd like to submit the PR, but just wanted to ask first in case I'm missing some reason not to. I think Composer wouldn't be affected because the class is imported with `import com.gojuno.commander.android.*`.

**Comment by artem-zinnatullin** [comment]
Oh lol, yep we should rename the file, PR welcome :)

**Comment by koral--** [comment]
This line also can be updated:
https://github.com/gojuno/commander/blob/master/android/src/main/kotlin/com/gojuno/commander/android/Adb.kt#L37

**Comment by Sloy** [comment]
Woops! Totally forgot about this 🤦‍♂️
