### ISSUE TITLE
Consider separating os and android modules to different repos.

### ISSUE THREAD

**Issue by igor-korotenko** [gojuno/commander#3]
Seems that this two modules are loosely coupled and maintaining them in single repo introduces a bit of ambiguity.

**Comment by artem-zinnatullin** [comment]
I agree and disagree, main point why it's in one repo at the moment is that it's easier to maintain one repo.

Also, `android` module depends on `os`, so coupling is not that loose.

I'm closing this for now, but feel free to comment and we'll definitely reopen it if major reasons for split would be found :)
