### ISSUE TITLE
Increase ADB install timeout or make it configurable

### ISSUE THREAD

**Issue by koral--** [gojuno/commander#7]
Timeout for APK installation is set to only 5 minutes:
https://github.com/gojuno/commander/blob/53236f00b4d7dd9e07246f3c8eb961739188dede/android/src/main/kotlin/com/gojuno/commander/android/Adb.kt#L61

I have a ~200 MB APK and a device connected remotely and 5 minutes is not enough.
In ddmlib (so also in spoon) there is a deafult timeout set to 5 s, in case of installation it seems to refer to a [single 64 KB chunk of data](https://android.googlesource.com/platform/tools/base/+/tools_r22/ddmlib/src/main/java/com/android/ddmlib/SyncService.java#671). Additionally default value can be increased using `com.android.ddmlib.DdmPreferences#setTimeOut`.

`adb install` constantly prints percentage during installation. Maybe installation timeout should occur when no new output is received within some time period e.g. 30 s?

**Comment by artem-zinnatullin** [comment]
Holy shit, PR welcome :)
